distro_links_manager:
    resource: "@DistroLinksManagerBundle/Controller/"
    type:     annotation
    prefix:   /

distro_core:
    resource: "@DistroCoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
